In [59]:
import numpy as np
import pandas as pd
import tensorflow as tf


In [60]:
tf.__version__

'2.1.0'

In [61]:
data=pd.read_csv("C:\\Users\ASUS\Desktop\\DATA_SCIENCE_FOLDER\\Data_Set.csv\\Part 1 - Artificial Neural Networks\\Churn_Modelling.csv")

In [62]:
data.head()

RowNumber  CustomerId   Surname  CreditScore Geography  Gender  Age  \
0          1    15634602  Hargrave          619    France  Female   42   
1          2    15647311      Hill          608     Spain  Female   41   
2          3    15619304      Onio          502    France  Female   42   
3          4    15701354      Boni          699    France  Female   39   
4          5    15737888  Mitchell          850     Spain  Female   43   

   Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMember  \
0       2       0.00              1          1               1   
1       1   83807.86              1          0               1   
2       8  159660.80              3          1               0   
3       1       0.00              2          0               0   
4       2  125510.82              1          1               1   

   EstimatedSalary  Exited  
0        101348.88       1  
1        112542.58       0  
2        113931.57       1  
3         93826.63       0  
4         79084.10       0

In [63]:
independent_v=data.iloc[:,3:-1].values
dependent_v=data.iloc[:,-1].values

In [64]:
independent_v

array([[619, 'France', 'Female', ..., 1, 1, 101348.88],
       [608, 'Spain', 'Female', ..., 0, 1, 112542.58],
       [502, 'France', 'Female', ..., 1, 0, 113931.57],
       ...,
       [709, 'France', 'Female', ..., 0, 1, 42085.58],
       [772, 'Germany', 'Male', ..., 1, 0, 92888.52],
       [792, 'France', 'Female', ..., 1, 0, 38190.78]], dtype=object)

In [65]:
#encode

from sklearn.preprocessing import LabelEncoder

l=LabelEncoder()

independent_v[:,2]=l.fit_transform(independent_v[:,2])



In [66]:
print (independent_v[:2])

[[619 'France' 0 42 2 0.0 1 1 1 101348.88]
 [608 'Spain' 0 41 1 83807.86 1 0 1 112542.58]]


In [67]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder

In [68]:
ct=ColumnTransformer(transformers=[("encoder",OneHotEncoder(),[1])],remainder="passthrough")
independent_v=np.array(ct.fit_transform(independent_v))


In [69]:
print (independent_v[:5])

[[1.0 0.0 0.0 619 0 42 2 0.0 1 1 1 101348.88]
 [0.0 0.0 1.0 608 0 41 1 83807.86 1 0 1 112542.58]
 [1.0 0.0 0.0 502 0 42 8 159660.8 3 1 0 113931.57]
 [1.0 0.0 0.0 699 0 39 1 0.0 2 0 0 93826.63]
 [0.0 0.0 1.0 850 0 43 2 125510.82 1 1 1 79084.1]]


In [70]:
from sklearn.model_selection import train_test_split

In [71]:
x_train,x_test,y_train,y_test=train_test_split(independent_v,dependent_v,test_size=0.2,random_state=0)

In [72]:
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
x_train=sc.fit_transform(x_train)
x_test=sc.transform(x_test)

In [76]:
ann=tf.keras.models.Sequential()
ann.add(tf.keras.layers.Dense(200,activation="relu"))
ann.add(tf.keras.layers.Dense(100,activation="relu"))
ann.add(tf.keras.layers.Dense(50,activation="relu"))
ann.add(tf.keras.layers.Dense(1,activation="sigmoid"))

In [82]:
ann.compile(optimizer="adam",loss="binary_crossentropy",metrics=["accuracy"])

In [117]:
ann.fit(x_train,y_train,batch_size=32,epochs=5)

Train on 8000 samples
Epoch 1/5
8000/8000 [==============================] - 4s 552us/sample - loss: 0.0473 - accuracy: 0.9837
Epoch 2/5
8000/8000 [==============================] - 0s 55us/sample - loss: 0.0485 - accuracy: 0.9834
Epoch 3/5
8000/8000 [==============================] - 0s 54us/sample - loss: 0.0521 - accuracy: 0.9835
Epoch 4/5
8000/8000 [==============================] - 0s 54us/sample - loss: 0.0394 - accuracy: 0.9862
Epoch 5/5
8000/8000 [==============================] - 0s 54us/sample - loss: 0.0423 - accuracy: 0.9854


In [124]:
ann.summary()

Model: "sequential_2"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense (Dense)                multiple                  2600      
_________________________________________________________________
dense_1 (Dense)              multiple                  20100     
_________________________________________________________________
dense_2 (Dense)              multiple                  5050      
_________________________________________________________________
dense_3 (Dense)              multiple                  51        
Total params: 27,801
Trainable params: 27,801
Non-trainable params: 0
_________________________________________________________________


In [131]:
y_pred=ann.predict(x_test)
y_pred=y_pred[(y_pred>0.5)]

In [133]:
len(y_pred)

403

In [127]:
from sklearn.metrics import confusion_matrix,accuracy_score

In [128]:
cm=confusion_matrix(y_pred,y_test)

In [129]:
cm
accuracy_score(y_pred,y_test)

0.808